version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: employit_db
    ports:
     - "5432:5432"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    container_name: backend

  frontend:
        image: "node:alpine"
        build: ./frontend
        command: npm run start
        container_name: frontend
        ports:
          - "3000:3000"
        volumes:
         - './employit:/code'
         - './node_modules:/code/node_modules/'
        environment:
         - CHOKIDAR_USEPOLLING=true